### ISSUE TITLE
Forage Straw Pickup

### ISSUE THREAD

**Issue by westor7** [GMNGjoy/FS22_PaperFactoryPlus#2]
Hello,

Sorry for posting this here, your work is amazing and i love it, but in https://github.com/GMNGjoy/FS22_ForageStrawPickup the `Issues` feature is missing so i cannot post there.

Can you add support for this mod https://www.farming-simulator.com/mod.php?lang=en&country=us&mod_id=294131&title=fs2022 and for https://www.farming-simulator.com/mod.php?lang=en&country=us&mod_id=225589&title=fs2022 in `Forage Straw Pickup` mod? and please if is possible to enable `Issues` tab in the project github for any future issues/suggestions.

- Thanks!

**Comment by GMNGjoy** [comment]
@westor7 unfortunately, I cannot directly include modifications to other author's mods within the ForageStrawPickup mod (to be released on ModHub), as that violates Giant's terms of service. I can, however create a private mod that can serve the same purpose, bespoke to the two mods in question. If you'd like that solution, please contact me on discord @gmngjoy.
